### ISSUE TITLE
Remove SendMailJob

### ISSUE THREAD

**Issue by DenTray** [RonasIT/laravel-empty-project#10]
Since Laravel has a ShouldQueue interface and we can use in on the Mail class and remove custom SendMailJob at all.

**Comment by pirs1337** [comment]
blocked from https://github.com/RonasIT/laravel-empty-project/issues/33

**Comment by pirs1337** [comment]
@DenTray, already removed in https://github.com/RonasIT/laravel-empty-project/issues/33

**Comment by DenTray** [comment]
@pirs1337 got it, thanks!
