### ISSUE TITLE
Enable throw mode for filesystem drivers

### ISSUE THREAD

**Issue by DenTray** [RonasIT/laravel-empty-project#108]
Each filesystem driver has `thow` option

<img width="583" alt="image" src="https://github.com/user-attachments/assets/ce52c5e1-9984-45de-8883-cef6d0350309">

We need to enable it for all drivers

**Comment by yogyrton** [comment]
@DenTray Done. Please check it

**Comment by DenTray** [comment]
@yogyrton thanks! looks good!
