### ISSUE TITLE
Update the laravel-swagger to the latest version

### ISSUE THREAD

**Issue by alinoksha** [RonasIT/laravel-empty-project#24]

**Comment by pirs1337** [comment]
@DenTray, you can test

**Comment by DenTray** [comment]
<img width="864" alt="image" src="https://user-images.githubusercontent.com/9486872/178645793-f81643c9-7a12-4347-b2e8-12d0a1389ddd.png">

@pirs1337 it seems to version is not updating automatically via `composer install`

**Comment by pirs1337** [comment]
@DenTray, please, test again

**Comment by DenTray** [comment]
@pirs1337 works fine now, thanks

@alinoksha FYI
