### ISSUE TITLE
Release new helpers and update helpers

### ISSUE THREAD

**Issue by pirs1337** [RonasIT/laravel-empty-project#33]
Please, release new helpers with changes from https://github.com/RonasIT/laravel-helpers/commit/1c2b1bf3e756ff281f4d4789084d1b885ab780a3 and update helpers to the released version.

**Comment by DenTray** [comment]
@pirs1337 Laravel-Helpers has been released, new version [2.1](https://github.com/RonasIT/laravel-helpers/releases/tag/2.1)

Could you please update Empty project for work with the new version

**Comment by pirs1337** [comment]
@DenTray, you can test

**Comment by DenTray** [comment]
@pirs1337 works fine, thanks!
