### ISSUE TITLE
Add  "Database\\Factories\\": "database/factories/" to composer autoload

### ISSUE THREAD

**Issue by Adil9994** [RonasIT/laravel-empty-project#53]
Related task https://github.com/RonasIT/laravel-entity-generator/issues/20
Fix: https://laravel.com/docs/8.x/upgrade#seeder-factory-namespaces
Related error:
  Class "Database\Factories\TestFactory" not found

  at vendor/laravel/framework/src/Illuminate/Database/Eloquent/Factories/Factory.php:814
    810▕     public static function factoryForModel(string $modelName)
    811▕     {
    812▕         $factory = static::resolveFactoryName($modelName);
    813▕         
  ➜ 814▕         return $factory::new();
    815▕     }
    816▕ 
    817▕     /**
    818▕      * Specify the callback that should be invoked to guess factory names based on dynamic relationship names.

@DenTray

**Comment by DenTray** [comment]
@Adil9994 got it! Please proceed

**Comment by Adil9994** [comment]
@DenTray done

**Comment by DenTray** [comment]
@Adil9994 works good, thanks!
