### ISSUE TITLE
Update Laravel to actual version

### ISSUE THREAD

**Issue by DenTray** [RonasIT/laravel-empty-project#8]
For Laravel >=9 package to work with GCS should be exchange from https://packagist.org/packages/superbalist/laravel-google-cloud-storage to [spatie/laravel-google-cloud-storage](https://packagist.org/packages/spatie/laravel-google-cloud-storage)

**Comment by pirs1337** [comment]
@DenTray, done

**Comment by DenTray** [comment]
@pirs1337 works fine, thanks!
